# Generated by Django 3.0.8 on 2020-08-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_board_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='x',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='y',
            field=models.IntegerField(null=True),
        ),
    ]
