version: '3.7'
# docker-compose up --build (시작 전에 DB를 위해 back서비스의 env파일 수정할 것)
# docker-compose down(프론트 앱 업데이트를 위해 front_app volume은 제거할 것)
# volume은 처음 생성 시, 해당 볼륨으로 접근하는 최초 컨테이너에 한해서만 데이터가 업데이트 되기 때문
# 즉, 프론트앱 볼륨이 잔류할 시 다음 빌드 배포에 대해 볼륨 내부 데이터는 업데이트 되지 않음
# 반대로 postgres가 데이터 저장을 위해 사용하는 볼륨은 절대 지우면 안되겠지;;;
services:
    psql:
        image: postgres:12.4-alpine
        volumes:
            - psql_data:/var/lib/postgresql/data/
        env_file:
            - ./postgres.env
    front:
        build:
            context: ./front
        volumes:
            - front_app:/front/build
        environment:
            - REACT_APP_API_HOST=http://freechart/api
    back:
        build:
            context: ./back
        env_file:
            - ./back/.env
        depends_on:
            - psql
    nginx:
        image: nginx:latest
        ports:
            - 80:8080
        volumes:
            # - /etc/nginx/ssl/: /etc/nginx/ssl/
            - front_app:/var/www/front/
            - ./nginx/freechart.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - back
            - front
        environment:
            - REACT_APP_API_HOST=http://freechart/api
    redis:
        image: "redis:alpine"
        ports:
            - 6379:6379
volumes:
    psql_data:
    front_app:

