version: '3.7'
# docker-compose build
# [DEV_DB_HOST=...] docker-compose up
services:
    front:
        build:
            context: ./front
        volumes:
            - ./front/build:/front/build
        env_file:
            - ./front/.env
    back:
        build:
            context: ./back
        ports:
            - 8000:8000
        env_file:
            - ./back/.env
    nginx:
        image: nginx:latest
        ports:
            - 80:8080
        volumes:
            - ./nginx/freechart.conf:/etc/nginx/conf.d/default.conf:ro
            - ./front/build:/var/www/front
        depends_on:
            - back
            - front
    redis:
        image: "redis:alpine"
        ports:
            - 6379:6379

