# Generated by Django 3.0.8 on 2020-07-14 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_sheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128, verbose_name='라벨')),
                ('sheet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.Sheet')),
            ],
            options={
                'verbose_name': 'node',
                'db_table': 'node',
            },
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128, verbose_name='라벨')),
                ('node1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node1', to='board.Node')),
                ('node2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node2', to='board.Node')),
                ('sheet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.Sheet')),
            ],
            options={
                'verbose_name': 'edge',
                'db_table': 'edge',
            },
        ),
    ]
