# Generated by Django 3.0.8 on 2020-07-29 03:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_sheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sheet',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=128, verbose_name='라벨')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='작성 날짜')),
                ('modify', models.DateTimeField(auto_now=True, verbose_name='수정 날짜')),
                ('deleted', models.BooleanField(default=False)),
                ('sheet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.Sheet')),
            ],
            options={
                'verbose_name': 'node',
                'db_table': 'node',
            },
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=128, verbose_name='라벨')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='작성 날짜')),
                ('modify', models.DateTimeField(auto_now=True, verbose_name='수정 날짜')),
                ('deleted', models.BooleanField(default=False)),
                ('node1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node1', to='board.Node')),
                ('node2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node2', to='board.Node')),
                ('sheet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.Sheet')),
            ],
            options={
                'verbose_name': 'edge',
                'db_table': 'edge',
            },
        ),
    ]
