# Generated by Django 3.0.8 on 2020-07-29 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20200729_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edge',
            old_name='node1',
            new_name='node_from',
        ),
        migrations.RenameField(
            model_name='edge',
            old_name='node2',
            new_name='node_to',
        ),
    ]
