# Generated by Django 3.0.8 on 2020-07-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_edge_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='edge',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='node',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sheet',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
