# Generated by Django 3.0.8 on 2020-08-06 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20200729_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.Board'),
        ),
    ]
