# Generated by Django 3.1 on 2020-08-24 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_auto_20200813_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='arrow',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='edge',
            name='dashes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='edge',
            name='width',
            field=models.IntegerField(default=3),
        ),
    ]
