# Generated by Django 3.1 on 2020-08-26 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_auto_20200825_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='arrow',
            field=models.IntegerField(default=1),
        ),
    ]
